name: "silive"
base_url: "https://api.queryly.com/v4/search.aspx"
query: "immigration"
output_dir: "output/silive"
headers:
  accept: "application/json"
  accept-language: "en-US,en;q=0.9,es;q=0.8"
  referer: "https://www.silive.com/"
  sec-ch-ua: '"Not A(Brand";v="8", "Chromium";v="132", "Google Chrome";v="132"'
  sec-ch-ua-mobile: "?0"
  sec-ch-ua-platform: '"Windows"'
  sec-fetch-dest: "script"
  sec-fetch-mode: "no-cors"
  sec-fetch-site: "cross-site"
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
parameters:
  queryly_key: "be04469294ea4727"
  initialized: 1
  callback: ""
  extendeddatafields: ""
  timezoneoffset: 300
  uiversion: 1
  batchsize: 30
field_mappings:
  link: "link"
  date: "pubdate"
  title: "title"
  description: "description"
pagination:
  type: "offset"
  parameter: "endindex"
  batch_size: 30
  total_field: "metadata.total"
request_settings:
  delay: 1
  max_retries: 3
  retry_delay: 5