name: "thecity"
base_url: "https://public-api.wordpress.com/rest/v1.3/sites/224811423/search"
query: "immigration"
output_dir: "output/thecity"
headers:
  accept: "*/*"
  accept-language: "en-US,en;q=0.9,es;q=0.8"
  origin: "https://www.thecity.nyc"
  priority: "u=1, i"
  referer: "https://www.thecity.nyc/"
  sec-ch-ua: '"Not A(Brand";v="8", "Chromium";v="132", "Google Chrome";v="132"'
  sec-ch-ua-mobile: "?0"
  sec-ch-ua-platform: '"Windows"'
  sec-fetch-dest: "empty"
  sec-fetch-mode: "cors"
  sec-fetch-site: "cross-site"
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
parameters:
  fields:
    - "date"
    - "permalink.url.raw"
    - "tag.name.default"
    - "category.name.default"
    - "post_type"
    - "shortcode_types"
    - "forum.topic_resolved"
    - "has.image"
    - "image.url.raw"
    - "image.alt_text"
  highlight_fields:
    - "title"
    - "content"
    - "comments"
  sort: "date_desc"
  size: 20
field_mappings:
  link: "fields.permalink.url.raw"
  date: "fields.date"
  title: "fields.title.default"
  description: "highlight.content"
pagination:
  type: "cursor"
  parameter: "page_handle"
  response_field: "page_handle"
request_settings:
  delay: 1
  max_retries: 3
  retry_delay: 5